#!/bin/bash
#SBATCH --job-name=putidaTest
#SBATCH --partition=long
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=36
#SBATCH --time=72:00:00
#SBATCH --account=microenviro
#SBATCH --output=bcol.out
#SBATCH --error=bcol.err
source /projects/microenviro/ofoam6_cray_mpich/OpenFOAM-dev/etc/bashrc
srun -n 72 putidaFoam -parallel -fileHandler collated
